import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import { Link as Scroll } from "react-scroll";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "My Profile | Yaha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-dvh`}>
        <header className="h-16 flex items-center mx-auto px-7 py-14 bg-orange-50	">
          {/* <Scroll to="top" smooth={true} duration={500}> */}
            <img src="/images/img_profile.jpg" alt="Scroll to top" className="w-16 h-16 rounded-full border border-black"/>
          {/* </Scroll> */}
          <div id="top"></div>
        </header>

        {children}

        <footer className="sticky top-full h-16 flex items-center mx-auto py-1 justify-center bg-black text-white">
          <small>&copy; Kosuke Yahara, All Rights Reserved.</small>
        </footer>
      </body>
    </html>
  );
}
