import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import { Link as Scroll } from "react-scroll";
import ScrollComponent from '@/components/ScrollComponent/ScrollComponent';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "My Profile | Yaha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-dvh`}>
        <header className="items-center mx-auto bg-orange-50">
          <ScrollComponent />
        </header>

        {children}

        <footer className="sticky top-full h-16 flex items-center mx-auto py-1 justify-center bg-black text-white">
          <small>&copy; Kosuke Yahara, All Rights Reserved.</small>
        </footer>
      </body>
    </html>
  );
}
